# Generated by Django 6.0.3 on 2026-05-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='載具名稱/編號')),
                ('device_type', models.CharField(choices=[('ipad', 'iPad'), ('chromebook', 'Chromebook'), ('surface_go', 'SurfaceGo'), ('acer_laptop', 'Acer筆電')], max_length=20, verbose_name='載具類型')),
                ('section', models.CharField(choices=[('junior', '國中部'), ('senior', '高中部')], max_length=10, verbose_name='適用學部')),
                ('is_bulk', models.BooleanField(default=False, verbose_name='是否為散裝')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用(隱藏/刪除開關)')),
            ],
        ),
        migrations.CreateModel(
            name='RentalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='租借日期')),
                ('period', models.IntegerField(choices=[(1, '第 1 節'), (2, '第 2 節'), (3, '第 3 節'), (4, '第 4 節'), (5, '第 5 節'), (6, '第 6 節'), (7, '第 7 節')], verbose_name='節次')),
                ('school_section', models.CharField(choices=[('junior', '國中部'), ('senior', '高中部')], max_length=10, verbose_name='學部')),
                ('student_name', models.CharField(max_length=50, verbose_name='學生名字')),
                ('student_class', models.CharField(max_length=50, verbose_name='班級')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='借用數量')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.device', verbose_name='所選載具')),
            ],
        ),
    ]
